apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    openshift.io/installed-from: tektonhub
    tekton.dev/categories: Security
    tekton.dev/displayName: Policy check an image with Red Hat Advanced Cluster Security
    tekton.dev/pipelines.minVersion: 0.18.0
    tekton.dev/platforms: linux/amd64
    tekton.dev/tags: security
  name: rhacs-image-check
  namespace: demo
  labels:
    app.kubernetes.io/version: '4.10'
spec:
  description: >-
    Policy check an image with Red Hat Advanced Cluster Security.

    This tasks allows you to check an image against build-time policies and
    apply enforcement to fail builds.  It's a companion to the rhacs-image-scan
    task, which returns full vulnerability scan results for an image.
  params:
    - default: rox-central-endpoint
      description: >-
        Name of secret containing the address:port tuple for RHACS Stackrox
        Central.
      name: rox_central_endpoint
      type: string
    - default: rox-api-token
      description: >-
        Name of secret containing the RHACS StackRox API token with CI
        permissions.
      name: rox_api_token
      type: string
    - default: 'quay.io/stackrox-io/roxctl:latest'
      description: Image providing the roxctl tool.
      name: rox_image
      type: string
    - default: $(params.IMAGE)
      description: >
        Full name of image to check.

        Examples: 'gcr.io/rox/sample:5.0-rc1', '$(params.IMAGE)',
        '$(params.IMAGE)@$(tasks.buildah.results.IMAGE_DIGEST)'
      name: image
      type: string
    - default: table
      description: Results output format (csv | json | junit | table)
      name: output_format
      type: string
    - default: 'false'
      description: >
        Do not verify TLS certificates.


        When set to "true", skip verifying the TLS certs of the Central endpoint
        and registry.
      name: insecure-skip-tls-verify
      type: string
  results:
    - description: Output of `roxctl image check`
      name: check_output
      type: string
  steps:
    - args:
        - image
        - check
        - '--endpoint=$(ROX_CENTRAL_ENDPOINT)'
        - '--insecure-skip-tls-verify=$(INSECURE)'
        - '--output=$(OUTPUT)'
        - '--image=$(IMAGE)'
      env:
        - name: HOME
          value: /tekton/home
        - name: IMAGE
          value: $(params.image)
        - name: INSECURE
          value: $(params.insecure-skip-tls-verify)
        - name: OUTPUT
          value: $(params.output_format)
        - name: ROX_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: rox_api_token
              name: $(params.rox_api_token)
        - name: ROX_CENTRAL_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: rox_central_endpoint
              name: $(params.rox_central_endpoint)
      image: $(params.rox_image)
      name: rox-image-check
      resources: {}
