
# (1)
app:
  baseUrl: https://backstage-developer-hub-backstage.apps.piomin.eastus.aroapp.io

backend:
  baseUrl: https://backstage-developer-hub-backstage.apps.piomin.eastus.aroapp.io

# (2)
auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}

# (3)
proxy:
  endpoints:
    /sonarqube:
      target: ${SONARQUBE_URL}/api
      allowedMethods: ['GET', 'POST']
      auth: "${SONARQUBE_TOKEN}:"

# (4)
catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    - type: url
      target: https://github.com/piomin/backstage-templates/blob/master/templates.yaml
      rules:
        - allow: [Template, Location]

# (5)
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

sonarqube:
  baseUrl: https://sonarcloud.io
  apiKey: ${SONARQUBE_TOKEN}